name: Python Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello-World-Python
        uses: Hello-World-Python/.github/workflows/deploy.yml


  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.3'

      - name: Deploy to Production
        run: |
          #  deployment commands
         
